### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by getwebem** [vemuez/react-boilerplate#1]
Hi, 
when I npm start this boilerplate i get the, "Uncaught SyntaxError: Unexpected token < " in the bundle.min.js

**Comment by YussufElarif** [comment]
Do you have Powershell in your machine?
I've just removed the need for powershell cli and updated the package.json. So it should be good to go.
 
Pull in the latest master. 
```
npm install
npm start 
```
and you should be good to go.
